# -*- coding: utf-8 -*-
"""AI_Fitness_&_Health_Dashboard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y0G4Y2rMV16L_EHoReVJCSgHouxAO10D
"""

# Commented out IPython magic to ensure Python compatibility.
 # Import Streamlit library and give it a short name "st"
# %pip install streamlit
import streamlit as st

# ---------------- PAGE CONFIG ----------------
st.set_page_config(
    page_title="Smart BMI Calculator",
    page_icon="🏋️",
    layout="centered"
)

# ---------------- CUSTOM CSS ----------------
st.markdown("""
<style>
.main {
    background-color: #0E1117;
}

.title {
    text-align: center;
    font-size: 50px;
    font-weight: bold;
    color: #4CAF50;
}

.subtitle {
    text-align: center;
    color: #AAAAAA;
    margin-bottom: 30px;
}

.result-box {
    padding: 20px;
    border-radius: 15px;
    text-align: center;
    font-size: 24px;
    font-weight: bold;
    background: linear-gradient(135deg,#4CAF50,#2196F3);
    color: white;
}
</style>
""", unsafe_allow_html=True)

# ---------------- HEADER ----------------
st.markdown(
    '<div class="title">🏋️ Smart BMI Calculator</div>',
    unsafe_allow_html=True
)

st.markdown(
    '<div class="subtitle">Know Your Health Status Instantly</div>',
    unsafe_allow_html=True
)

st.divider()

# ---------------- INPUTS ----------------
col1, col2 = st.columns(2)

with col1:
    weight = st.number_input(
        "⚖️ Weight (kg)",
        min_value=1.0,
        max_value=300.0,
        value=70.0
    )

with col2:
    height = st.number_input(
        "📏 Height (cm)",
        min_value=50.0,
        max_value=250.0,
        value=170.0
    )

age = st.slider(
    "🎂 Age",
    min_value=10,
    max_value=100,
    value=25
)

gender = st.radio(
    "👤 Gender",
    ["Male", "Female"],
    horizontal=True
)

st.divider()

# ---------------- CALCULATE ----------------
if st.button("🚀 Calculate My BMI", use_container_width=True):

    height_m = height / 100
    bmi = weight / (height_m ** 2)

    st.markdown(
        f"""
        <div class="result-box">
        Your BMI is <br>
        {bmi:.2f}
        </div>
        """,
        unsafe_allow_html=True
    )

    st.write("")

    # Progress Bar
    progress = min(int((bmi / 40) * 100), 100)
    st.progress(progress)

    # Category
    if bmi < 18.5:
        category = "🔵 Underweight"
        tip = "Increase calorie intake and focus on protein-rich foods."

    elif bmi < 25:
        category = "🟢 Healthy Weight"
        tip = "Excellent! Maintain your current lifestyle."

    elif bmi < 30:
        category = "🟠 Overweight"
        tip = "Try regular exercise and balanced nutrition."

    else:
        category = "🔴 Obese"
        tip = "Consult a healthcare professional and start a fitness plan."

    st.subheader(category)

    st.info(f"💡 Health Tip: {tip}")

    # Health Score
    score = max(0, 100 - abs(22 - bmi) * 5)

    st.metric(
        label="🏆 Health Score",
        value=f"{score:.0f}/100"
    )

    # Recommendation
    st.subheader("📋 Recommendations")

    st.write("""
    ✅ Drink 2-3 liters of water daily

    ✅ Exercise at least 30 minutes a day

    ✅ Get 7-8 hours of sleep

    ✅ Eat more fruits and vegetables

    ✅ Avoid excessive processed food
    """)

# ---------------- BMI TABLE ----------------
st.divider()

st.subheader("📊 BMI Classification")

st.table({
    "Category": [
        "Underweight",
        "Healthy Weight",
        "Overweight",
        "Obese"
    ],
    "BMI Range": [
        "<18.5",
        "18.5 - 24.9",
        "25 - 29.9",
        "30+"
    ]
})

st.caption(
    "⚠️ BMI is a general health indicator and should not replace professional medical advice."
)

