# -*- coding: utf-8 -*-
"""Basic_Chatbot_Create.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FCMg28yIkPSpEpi6mUgbLuOeIoSBZqvi
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install streamlit
import streamlit as st

st.title("Basic Chatbot")

# Store Chat history
if "message" not in st.session_state:
  st.session_state.message = []

# Display Previous messsage
for message in st.session_state.message:
  with st.chat_message(message["role"]):
    st.write(message["content"])

# User Input
user_input = st.chat_input("Type Your Message...")

if user_input:
  # Show user message
  st.session_state.message.append(
      {"role":"user","content":user_input}
  )

with st.chat_message("user"):
  st.write(user_input)

# Simple Chatbot Logic
user_input = user_input or ""

if "hello" in user_input.lower():
    bot_reply = "Hello! How can I help you?"
elif "name" in user_input.lower():
  bot_reply = "I am a simple streamlit chatbot."
elif "bye" in user_input.lower():
  bot_reply = "Goodbye! Have a great day."
else:
  bot_reply = "Sorry, I don't understand that yet."

# Show bot Response

st.session_state.message.append(
    {"role":"assistant", "content": bot_reply}
)


with st.chat_message("assistant"):
  st.write(bot_reply)

