# -*- coding: utf-8 -*-
"""Password_Checker_Ranjeet.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QAcDksRyyMpknCX_EbB6453IDyZEVQSA
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install streamlit
import streamlit as st

st.title("Password Checker")

pwd=st.text_input(
    "Password",
    type="password"
)

if st.button("Check"):

    score=0

    if len(pwd)>=8:
        score+=1

    if any(c.isdigit() for c in pwd):
        score+=1

    if any(c.isupper() for c in pwd):
        score+=1

    st.write("Strength:",score,"/3")

